In [ ]:
import os
import requests

In [ ]:
# Folder to store downloaded CSVs
os.makedirs("raw_data", exist_ok=True)

# List of monthly CSV URLs (ADD MORE MONTHS HERE)
urls = {
    "2025_01": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/3b10f5a3-58f0-4fa6-9210-ae950a185ab8/download/dublin-bikes_station_status_012025.csv",
    "2025_02": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/2bac02ee-d480-48d5-bece-b3968fb74c30/download/dublin-bikes_station_status_022025.csv",
    "2025_03": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/ef819959-8183-45d4-a0bb-8027cf8f0876/download/dublin-bikes_station_status_032025.csv",
    "2025_04": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/ab8604b5-9fe4-4e7b-b112-6ebacdfd039d/download/dublin-bikes_station_status_042025.csv",
    "2025_05": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/b67b71f3-311e-4206-aed1-ce0c958947c9/download/dublin-bikes_station_status_052025.csv",
    "2025_06": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/11fd116e-760a-4237-9bcf-abbace46a32a/download/dublin-bikes_station_status_062025.csv",
    "2025_07": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/5b5afbcc-61e0-48d0-870e-a22df2ea4793/download/dublin-bikes_station_status_072025.csv",
    "2025_08": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/1cb1e957-3600-4cfc-abf7-6d5749108d4e/download/dublin-bikes_station_status_082025.csv",

    # "2025_09": "https://data.smartdublin.ie/dataset/dublinbikes-api/resource/xxxxxxxx/download/dublin-bikes_station_status_092025.csv",
    # "2025_10": "https://data.smartdublin.ie/dataset/dublinbikes-api/resource/yyyyyyyy/download/dublin-bikes_station_status_102025.csv",
    # "2025_11": "https://data.smartdublin.ie/dataset/dublinbikes-api/resource/zzzzzzzz/download/dublin-bikes_station_status_112025.csv",
    # "2025_12": "https://data.smartdublin.ie/dataset/dublinbikes-api/resource/xxxxxxxx/download/dublin-bikes_station_status_122025.csv",



    "2024_08": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/6c13cb05-f31e-414e-a8be-16f2d9f4e53e/download/dublin-bikes_station_status_082024.csv",
    "2024_09": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/168f55b8-1c3d-4fd3-95b9-f92f388c772a/download/dublin-bikes_station_status_092024.csv",
    "2024_10": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/f9182676-043d-41dc-a8d4-fe602f677a0d/download/dublin-bikes_station_status_102024.csv",
    "2024_11": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/578d5726-8e59-4d15-84d0-bb755c530e22/download/dublin-bikes_station_status_112024.csv",
    "2024_12": "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/215455d4-6028-4035-aca6-455e48ba80f1/download/dublin-bikes_station_status_122024.csv"
 }

In [ ]:
for month, url in urls.items():
    file_path = f"raw_data/dublinbikes_{month}.csv"
    response = requests.get(url)

    if response.status_code == 200:
        with open(file_path, "wb") as f:
            f.write(response.content)
        print(f"Downloaded: {file_path}")
    else:
        print(f"Failed to download {month}")

Downloaded: raw_data/dublinbikes_2025_01.csv
Downloaded: raw_data/dublinbikes_2025_02.csv
Downloaded: raw_data/dublinbikes_2025_03.csv
Downloaded: raw_data/dublinbikes_2025_04.csv
Downloaded: raw_data/dublinbikes_2025_05.csv
Downloaded: raw_data/dublinbikes_2025_06.csv
Downloaded: raw_data/dublinbikes_2025_07.csv
Downloaded: raw_data/dublinbikes_2025_08.csv
Downloaded: raw_data/dublinbikes_2024_08.csv
Downloaded: raw_data/dublinbikes_2024_09.csv
Downloaded: raw_data/dublinbikes_2024_10.csv
Downloaded: raw_data/dublinbikes_2024_11.csv
Downloaded: raw_data/dublinbikes_2024_12.csv

Merge all CSVs into one history file

In [ ]:
import pandas as pd
import glob

# Read all CSV files
csv_files = glob.glob("raw_data/*.csv")

df_list = []
for file in csv_files:
    df = pd.read_csv(file)
    df_list.append(df) #[]

# Combine into single DataFrame
history_df = pd.concat(df_list, ignore_index=True)

# Save final merged file
history_df.to_csv("dublinbikes_history.csv", index=False)

print("Merged file saved as dublinbikes_history.csv")

Merged file saved as dublinbikes_history.csv

In [ ]:
history_df.shape

(7416360, 15)

In [ ]:
#600,000

In [ ]:
history_df=pd.read_csv("dublinbikes_history.csv")

In [ ]:
history_df.columns

Index(['system_id', 'last_reported', 'station_id', 'num_bikes_available',
       'num_docks_available', 'is_installed', 'is_renting', 'is_returning',
       'name', 'short_name', 'address', 'lat', 'lon', 'region_id', 'capacity'],
      dtype='object')

In [ ]:
history_df['last_reported']

0          2024-09-01 00:05:00
1          2024-09-01 00:05:00
2          2024-09-01 00:05:00
3          2024-09-01 00:05:00
4          2024-09-01 00:05:00
                  ...
7416355    2025-02-28 23:55:00
7416356    2025-02-28 23:55:00
7416357    2025-02-28 23:55:00
7416358    2025-02-28 23:55:00
7416359    2025-02-28 23:55:00
Name: last_reported, Length: 7416360, dtype: object

In [ ]:
history_df.shape

(7416360, 15)

In [11]:
# Convert timestamp to datetime
#history_df["last_reported"] = pd.to_datetime(history_df["last_reported"], unit="ms")

# Sort properly
history_df = history_df.sort_values(["station_id", "last_reported"])

# Keep useful columns
history_df = history_df[
    ["station_id", "name", "num_bikes_available","num_docks_available", "is_renting", "is_returning","last_reported", "capacity", "lat","lon" ]
]

history_df.to_csv("dublinbikes_history_clean.csv", index=False)

In [12]:
history_df.isna().sum()

station_id             0
name                   0
num_bikes_available    0
num_docks_available    0
is_renting             0
is_returning           0
last_reported          0
capacity               0
lat                    0
lon                    0
dtype: int64